/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Util.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CleanerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CleanerFrame
     */
    public CleanerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCleanerContactNumber = new javax.swing.JTextField();
        txtCleanerID = new javax.swing.JTextField();
        txtCleanerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCleanerEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCleanerCompanyName1 = new javax.swing.JTextField();
        btnViewCleaner = new javax.swing.JButton();
        btnUpdateCleaner = new javax.swing.JButton();
        btnDeleteCleaner = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddCleaner = new javax.swing.JButton();
        btnClearCleaners = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTextArea1.setBackground(new java.awt.Color(51, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Cleaners Management");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cleaner Company Name:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cleaner ID:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cleaner Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Cleaner Contact Number:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Cleaner Email:");

        btnViewCleaner.setText("View Cleaner");
        btnViewCleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCleanerActionPerformed(evt);
            }
        });

        btnUpdateCleaner.setText("Update Cleaner");
        btnUpdateCleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCleanerActionPerformed(evt);
            }
        });

        btnDeleteCleaner.setText("Delete Cleaner");
        btnDeleteCleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCleanerActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CleanerID", "Cleaner Name", "Cleaner Company Name", "Cleaner Contact Number", "Cleaner Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnAddCleaner.setText("Add Cleaner");
        btnAddCleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCleanerActionPerformed(evt);
            }
        });

        btnClearCleaners.setText("Clear Cleaner");
        btnClearCleaners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCleanersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCleanerContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCleanerName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCleanerCompanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCleanerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnViewCleaner)
                                .addGap(36, 36, 36)
                                .addComponent(btnUpdateCleaner)
                                .addGap(46, 46, 46)
                                .addComponent(btnDeleteCleaner)
                                .addGap(41, 41, 41)
                                .addComponent(btnClearCleaners))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(txtCleanerID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCleaner)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2)
                    .addContainerGap(470, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtCleanerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCleanerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCleanerContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCleanerCompanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCleanerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCleaner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateCleaner)
                    .addComponent(btnDeleteCleaner)
                    .addComponent(btnAddCleaner)
                    .addComponent(btnClearCleaners))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCleanerActionPerformed
        
       String id = txtCleanerID.getText().trim();
    String name = txtCleanerName.getText().trim();
    String company = txtCleanerCompanyName1.getText().trim();
    String contact = txtCleanerContactNumber.getText().trim();
    String email = txtCleanerEmail.getText().trim();
    
    if (id.isEmpty() || name.isEmpty() || company.isEmpty() || contact.isEmpty() || email.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in the required fields.");
        return;
    }
    // 2. Validate Numbers
    if (!id.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cleaner ID must contain numbers only.");
        return;
    }
    if (!contact.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Contact Number must contain numbers only.");
        return;
    }
    
    // 3. Validate Text
    if (!name.matches("[a-zA-Z\\s.]+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cleaner Name cannot contain numbers.");
        return;
    }
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    if (!email.matches(emailRegex)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid email address (e.g., name@example.com).");
        return;
    }
    else{
        
        javax.swing.JOptionPane.showMessageDialog(this,"Data added Succesfully!");
    }
        // Add data to JTable
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{id, name, company, contact, email});
    
    
        
    }//GEN-LAST:event_btnAddCleanerActionPerformed

    private void btnViewCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCleanerActionPerformed
      javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    int rowCount = model.getRowCount();
    
    // Check if the table is empty
    if (rowCount == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No supplier records found in the table.");
        return;
    }
    
    // Create a list model to store formatted text lines
    javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
    
    // Loop through table rows and format the data for the list view
    for (int i = 0; i < rowCount; i++) {
        String id = model.getValueAt(i, 0).toString();
        String name = model.getValueAt(i, 1).toString();
        String company = model.getValueAt(i, 2).toString();
        String contact = model.getValueAt(i,3).toString();
        String email = model.getValueAt(i,4).toString();
        
        
        listModel.addElement(String.format("ID: %s | Name: %s | Company: %s|Contact:%s|Email:%s", id, name, company,contact,email));
    }
    
    // Wrap the list in a scrollable panel
    javax.swing.JList<String> supplierList = new javax.swing.JList<>(listModel);
    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(supplierList);
    scrollPane.setPreferredSize(new java.awt.Dimension(400, 200));
    
    // Display the pop-up list view
    javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Current Suppliers List", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewCleanerActionPerformed

    private void btnUpdateCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCleanerActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row from the table to update.");
        return;
    }
    
    String id = txtCleanerID.getText().trim();
    String name = txtCleanerName.getText().trim();
    String company = txtCleanerCompanyName1.getText().trim();
    String contact = txtCleanerContactNumber.getText().trim();
    String email = txtCleanerEmail.getText().trim();
    
    // Apply same validation rules for updates
    if (!id.matches("\\d+") || !contact.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID and Contact Number must be numeric.");
        return;
    }
    if (!name.matches("[a-zA-Z\\s.]+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Name cannot contain numbers.");
        return;
    }
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    if (!email.matches(emailRegex)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid supplier email address.");
        return;
    }
    model.setValueAt(id, selectedRow, 0);
    model.setValueAt(name, selectedRow, 1);
    model.setValueAt(company, selectedRow, 2);
    model.setValueAt(contact, selectedRow, 3);
    model.setValueAt(txtCleanerEmail.getText().trim(), selectedRow, 4);
    
    javax.swing.JOptionPane.showMessageDialog(this, "Update Successful!");
    }//GEN-LAST:event_btnUpdateCleanerActionPerformed

    private void btnDeleteCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCleanerActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow >= 0) {
        model.removeRow(selectedRow);
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    }
    }//GEN-LAST:event_btnDeleteCleanerActionPerformed

    private void btnClearCleanersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCleanersActionPerformed
       clearFields();
    }//GEN-LAST:event_btnClearCleanersActionPerformed
    private void clearFields() {
    txtCleanerID.setText("");
    txtCleanerName.setText("");
    txtCleanerCompanyName1.setText("");
    txtCleanerContactNumber.setText("");
    txtCleanerEmail.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCleaner;
    private javax.swing.JButton btnClearCleaners;
    private javax.swing.JButton btnDeleteCleaner;
    private javax.swing.JButton btnUpdateCleaner;
    private javax.swing.JButton btnViewCleaner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCleanerCompanyName1;
    private javax.swing.JTextField txtCleanerContactNumber;
    private javax.swing.JTextField txtCleanerEmail;
    private javax.swing.JTextField txtCleanerID;
    private javax.swing.JTextField txtCleanerName;
    // End of variables declaration//GEN-END:variables

    private static class txtCleanerId {

        public txtCleanerId() {
        }
    }
}
