
package views;
import dao.StockIssuanceDAO;
import database.DBConnection;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class IssueMaterialForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueMaterialForm.class.getName());

    private void loadCleaners() {

    try {

        Connection conn =
                DBConnection.getConnection();

        String sql =
            "SELECT cleaner_id, first_name, last_name " +
            "FROM cleaners";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while (rs.next()) {

            String item =
                rs.getInt("cleaner_id")
                + " - "
                + rs.getString("first_name")
                + " "
                + rs.getString("last_name");

            cmbCleaner.addItem(item);
        }

    } catch (Exception e) {

        e.printStackTrace();
    }
}
    
private void loadMaterials() {

    try {

        Connection conn =
                DBConnection.getConnection();

      String sql =
    "SELECT material_id, material_name, quantity " +
    "FROM materials " +
    "ORDER BY material_name";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while (rs.next()) {

            String item =
             rs.getInt("material_id")
                + " - "
                + rs.getString("material_name")
                + " (Stock: "
                + rs.getInt("quantity")
                + ")";

            cmbMaterial.addItem(item);
        }

    } catch (Exception e) {

        e.printStackTrace();
    }
}
    
    
    public IssueMaterialForm() {
        initComponents();
        
        setTitle(
        "University Cleaning Inventory System");
        
        setLocationRelativeTo(null);
        
        
         cmbCleaner.removeAllItems();
         cmbMaterial.removeAllItems();

        
        loadCleaners();
        loadMaterials();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCleaner = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        cmbCleaner = new javax.swing.JComboBox<>();
        cmbMaterial = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        btnIssue = new javax.swing.JButton();
        lblCleaner1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 193, 169));

        lblCleaner.setText("Cleaner:");

        lblMaterial.setText("Material:");

        lblQuantity.setText("Quantity:");

        btnIssue.setText("Issue Material");
        btnIssue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 218, 186), null, null, new java.awt.Color(255, 231, 169)));
        btnIssue.addActionListener(this::btnIssueActionPerformed);

        lblCleaner1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCleaner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCleaner1.setText("Issue Cleaning Materials");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCleaner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblCleaner1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnIssue)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCleaner1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCleaner)
                    .addComponent(cmbCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaterial)
                    .addComponent(cmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIssue)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
      try {

        if (txtQuantity.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a quantity.");

            return;
        }

        String cleanerText =
        cmbCleaner.getSelectedItem().toString();

        int cleanerId =
        Integer.parseInt(
                cleanerText.split(" - ")[0]);

        String materialText =
        cmbMaterial.getSelectedItem().toString();

        int materialId =
        Integer.parseInt(
                materialText.split(" - ")[0]);

        int quantity =
                Integer.parseInt(
                        txtQuantity.getText());

        if (quantity <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Quantity must be greater than zero.");

            return;
        }

        StockIssuanceDAO dao =
                new StockIssuanceDAO();

        boolean success =
                dao.issueMaterial(
                        cleanerId,
                        materialId,
                        quantity);

        if (success) {

            JOptionPane.showMessageDialog(
                    this,
                    "Material Issued Successfully");
            
            cmbMaterial.removeAllItems();
            loadMaterials();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Insufficient Stock");
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnIssueActionPerformed

   
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueMaterialForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssue;
    private javax.swing.JComboBox<String> cmbCleaner;
    private javax.swing.JComboBox<String> cmbMaterial;
    private javax.swing.JLabel lblCleaner;
    private javax.swing.JLabel lblCleaner1;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
