/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import util.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class MaterialFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaterialFrame.class.getName());

    /**
     * Creates new form MaterialFrame
     */
    public MaterialFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnMAdd = new javax.swing.JButton();
        btnMView = new javax.swing.JButton();
        btnMUpdate = new javax.swing.JButton();
        btnMDelete = new javax.swing.JButton();
        btnMReturn = new javax.swing.JButton();
        txtMMatID = new javax.swing.JTextField();
        txtMMatName = new javax.swing.JTextField();
        txtMMatQuantity = new javax.swing.JTextField();
        txtMMatReorder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Materials");

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaterialID", "Name", "Quantity", "ReorderLevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMaterial.getTableHeader().setReorderingAllowed(false);
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterial);

        btnMAdd.setText("Add Material");
        btnMAdd.addActionListener(this::btnMAddActionPerformed);

        btnMView.setText("View Material");
        btnMView.addActionListener(this::btnMViewActionPerformed);

        btnMUpdate.setText("Update Material");
        btnMUpdate.addActionListener(this::btnMUpdateActionPerformed);

        btnMDelete.setText("Delete Material");
        btnMDelete.addActionListener(this::btnMDeleteActionPerformed);

        btnMReturn.setText("Return");
        btnMReturn.addActionListener(this::btnMReturnActionPerformed);

        jLabel2.setText("ID:");

        jLabel3.setText("Name:");

        jLabel4.setText("Quantity:");

        jLabel5.setText("Reorder:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMAdd)
                        .addGap(27, 27, 27)
                        .addComponent(btnMView)
                        .addGap(18, 18, 18)
                        .addComponent(btnMUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnMDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMReturn)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMMatQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMMatReorder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtMMatID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtMMatName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatReorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMAdd)
                    .addComponent(btnMView)
                    .addComponent(btnMUpdate)
                    .addComponent(btnMDelete)
                    .addComponent(btnMReturn))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        String id = txtMMatID.getText().trim();
        String name = txtMMatName.getText().trim();
        String quantity = txtMMatQuantity.getText().trim();
        String reorder = txtMMatReorder.getText().trim();
        // Check empty fields
        if(id.isEmpty() | name.isEmpty() | quantity.isEmpty() | reorder.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in the required fields.");
        return;
        }
        //Check invalid inputs in number fields
        if(!id.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material ID must contain numbers only.");
        return;
        }
        if(!quantity.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material quantity must contain numbers only.");
        return;
        }
        if(!reorder.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material reorder must contain numbers only.");
        return;
        }
        //Check invalid input in text only fields
        if (!name.matches("[a-zA-Z\\s.]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cleaner Name cannot contain numbers.");
        return;
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Data added Succesfully!");
            // Add data to Table
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMaterial.getModel();
            model.addRow(new Object[]{id, name, quantity, reorder});
        }
    }//GEN-LAST:event_btnMAddActionPerformed

    private void btnMViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMViewActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMaterial.getModel();
        int rowCount = model.getRowCount();
    
        // Check if the table is empty
        if (rowCount == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No supplier records found in the table.");
            return;
        }
    
        // Create a list model to store formatted text lines
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
    
        // Loop through table rows and format the data for the list view
        for (int i = 0; i < rowCount; i++) {
            String id = model.getValueAt(i, 0).toString();
            String name = model.getValueAt(i, 1).toString();
            String quantity = model.getValueAt(i, 2).toString();
            String reorder = model.getValueAt(i,3).toString();
            listModel.addElement(String.format("ID: %s | Name: %s | Quantity: %s| Reorder:%s", id, name, quantity, reorder));
        }
    
        // Wrap the list in a scrollable panel
        javax.swing.JList<String> materialList = new javax.swing.JList<>(listModel);
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(materialList);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 200));
    
        // Display the pop-up list view
        javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Current Materail List", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMViewActionPerformed

    private void btnMUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUpdateActionPerformed
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMaterial.getModel();
    int selectedRow = tblMaterial.getSelectedRow();
    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row from the table to update.");
        return;
    }
        String id = txtMMatID.getText().trim();
        String name = txtMMatName.getText().trim();
        String quantity = txtMMatQuantity.getText().trim();
        String reorder = txtMMatReorder.getText().trim();
        // Check empty fields
        if(id.isEmpty() | name.isEmpty() | quantity.isEmpty() | reorder.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in the required fields.");
        return;
        }
        //Check invalid inputs in number fields
        if(!id.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material ID must contain numbers only.");
        return;
        }
        if(!quantity.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material quantity must contain numbers only.");
        return;
        }
        if(!reorder.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Material reorder must contain numbers only.");
        return;
        }
        //Check invalid input in text only fields
        if (!name.matches("[a-zA-Z\\s.]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cleaner Name cannot contain numbers.");
        return;
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Data updated Succesfully!");
            model.setValueAt(id, selectedRow, 0);
            model.setValueAt(name, selectedRow, 1);
            model.setValueAt(quantity, selectedRow, 2);
            model.setValueAt(reorder, selectedRow, 3);
        }
    }//GEN-LAST:event_btnMUpdateActionPerformed

    private void btnMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDeleteActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMaterial.getModel();
        int selectedRow = tblMaterial.getSelectedRow();
    
        if (selectedRow >= 0) {
            model.removeRow(selectedRow);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnMDeleteActionPerformed

    private void btnMReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMReturnActionPerformed

    private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMaterial.getModel();
    int selectedRow = tblMaterial.getSelectedRow();
        txtMMatID.setText(model.getValueAt(selectedRow, 0).toString());
        txtMMatName.setText(model.getValueAt(selectedRow, 1).toString());
        txtMMatQuantity.setText(model.getValueAt(selectedRow, 2).toString());
        txtMMatReorder.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tblMaterialMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MaterialFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMDelete;
    private javax.swing.JButton btnMReturn;
    private javax.swing.JButton btnMUpdate;
    private javax.swing.JButton btnMView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtMMatID;
    private javax.swing.JTextField txtMMatName;
    private javax.swing.JTextField txtMMatQuantity;
    private javax.swing.JTextField txtMMatReorder;
    // End of variables declaration//GEN-END:variables
}
