/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import util.DBConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.MaterialController;
/**
 *
 * @author Paul
 */
public class MaterialFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaterialFrame.class.getName());

    private void applyDarkMode() {
        getContentPane().setBackground(new java.awt.Color(15, 23, 42));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(226, 232, 240));
        jLabel3.setForeground(new java.awt.Color(226, 232, 240));
        jLabel4.setForeground(new java.awt.Color(226, 232, 240));
        jLabel5.setForeground(new java.awt.Color(226, 232, 240));
        txtMMatID.setBackground(new java.awt.Color(30, 41, 59));
        txtMMatID.setForeground(java.awt.Color.WHITE);
        txtMMatID.setCaretColor(java.awt.Color.WHITE);
        txtMMatName.setBackground(new java.awt.Color(30, 41, 59));
        txtMMatName.setForeground(java.awt.Color.WHITE);
        txtMMatName.setCaretColor(java.awt.Color.WHITE);
        txtMMatQuantity.setBackground(new java.awt.Color(30, 41, 59));
        txtMMatQuantity.setForeground(java.awt.Color.WHITE);
        txtMMatQuantity.setCaretColor(java.awt.Color.WHITE);
        txtMMatReorder.setBackground(new java.awt.Color(30, 41, 59));
        txtMMatReorder.setForeground(java.awt.Color.WHITE);
        txtMMatReorder.setCaretColor(java.awt.Color.WHITE);
        tblMaterial.setBackground(new java.awt.Color(30, 41, 59));
        tblMaterial.setForeground(new java.awt.Color(226, 232, 240));
        tblMaterial.setGridColor(new java.awt.Color(51, 65, 85));
        tblMaterial.setSelectionBackground(new java.awt.Color(51, 65, 85));
        tblMaterial.getTableHeader().setBackground(new java.awt.Color(30, 41, 59));
        tblMaterial.getTableHeader().setForeground(new java.awt.Color(148, 163, 184));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(15, 23, 42));
        repaint();
    }

    private void applyLightMode() {
        getContentPane().setBackground(new java.awt.Color(248, 250, 252));
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel2.setForeground(new java.awt.Color(15, 23, 42));
        jLabel3.setForeground(new java.awt.Color(15, 23, 42));
        jLabel4.setForeground(new java.awt.Color(15, 23, 42));
        jLabel5.setForeground(new java.awt.Color(15, 23, 42));
        txtMMatID.setBackground(java.awt.Color.WHITE);
        txtMMatID.setForeground(java.awt.Color.BLACK);
        txtMMatID.setCaretColor(java.awt.Color.BLACK);
        txtMMatName.setBackground(java.awt.Color.WHITE);
        txtMMatName.setForeground(java.awt.Color.BLACK);
        txtMMatName.setCaretColor(java.awt.Color.BLACK);
        txtMMatQuantity.setBackground(java.awt.Color.WHITE);
        txtMMatQuantity.setForeground(java.awt.Color.BLACK);
        txtMMatQuantity.setCaretColor(java.awt.Color.BLACK);
        txtMMatReorder.setBackground(java.awt.Color.WHITE);
        txtMMatReorder.setForeground(java.awt.Color.BLACK);
        txtMMatReorder.setCaretColor(java.awt.Color.BLACK);
        tblMaterial.setBackground(java.awt.Color.WHITE);
        tblMaterial.setForeground(new java.awt.Color(15, 23, 42));
        tblMaterial.setGridColor(new java.awt.Color(226, 232, 240));
        tblMaterial.setSelectionBackground(new java.awt.Color(226, 232, 240));
        tblMaterial.getTableHeader().setBackground(new java.awt.Color(241, 245, 249));
        tblMaterial.getTableHeader().setForeground(new java.awt.Color(100, 116, 139));
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        repaint();
    }

    public MaterialFrame() {
        initComponents();
        setLocationRelativeTo(null);
        if (util.ThemeManager.isDarkMode) {
            applyDarkMode();
            btnToggleTheme.setText("☀ Light");
        } else {
            applyLightMode();
            btnToggleTheme.setText("🌙 Dark");
        }
        tableModel = (DefaultTableModel) tblMaterial.getModel();
        materialController.loadMaterials(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnMAdd = new javax.swing.JButton();
        btnMView = new javax.swing.JButton();
        btnMUpdate = new javax.swing.JButton();
        btnMDelete = new javax.swing.JButton();
        btnMReturn = new javax.swing.JButton();
        txtMMatID = new javax.swing.JTextField();
        txtMMatName = new javax.swing.JTextField();
        txtMMatQuantity = new javax.swing.JTextField();
        txtMMatReorder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnToggleTheme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Materials");

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaterialID", "Name", "Quantity", "ReorderLevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMaterial.getTableHeader().setReorderingAllowed(false);
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterial);

        btnMAdd.setText("Add Material");
        btnMAdd.addActionListener(this::btnMAddActionPerformed);

        btnMView.setText("View Material");
        btnMView.addActionListener(this::btnMViewActionPerformed);

        btnMUpdate.setText("Update Material");
        btnMUpdate.addActionListener(this::btnMUpdateActionPerformed);

        btnMDelete.setText("Delete Material");
        btnMDelete.addActionListener(this::btnMDeleteActionPerformed);

        btnMReturn.setText("Back to Dashboard");
        btnMReturn.addActionListener(this::btnMReturnActionPerformed);

        jLabel2.setText("ID:");

        jLabel3.setText("Name:");

        jLabel4.setText("Quantity:");

        jLabel5.setText("Reorder:");

        btnToggleTheme.setText("☀ Light");
        btnToggleTheme.addActionListener(this::btnToggleThemeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMMatQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMMatReorder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtMMatID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtMMatName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(btnToggleTheme)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMAdd)
                        .addGap(27, 27, 27)
                        .addComponent(btnMView)
                        .addGap(18, 18, 18)
                        .addComponent(btnMUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnMDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnMReturn)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnToggleTheme))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMMatReorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMAdd)
                    .addComponent(btnMView)
                    .addComponent(btnMUpdate)
                    .addComponent(btnMDelete)
                    .addComponent(btnMReturn))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private final MaterialController materialController = new MaterialController();
    private DefaultTableModel tableModel;
    
    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        String error = materialController.addMaterial(txtMMatID.getText(), txtMMatName.getText(),
                txtMMatQuantity.getText(), txtMMatReorder.getText());
        if (error == null) {
            JOptionPane.showMessageDialog(this, "Material added successfully.");
            materialController.loadMaterials(tableModel);
        } else {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMAddActionPerformed

    private void btnMViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMViewActionPerformed
        String error = materialController.loadMaterials(tableModel);
    }//GEN-LAST:event_btnMViewActionPerformed

    private void btnMUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUpdateActionPerformed
        String error = materialController.updateMaterial(txtMMatID.getText(), txtMMatName.getText(),
                txtMMatQuantity.getText(), txtMMatReorder.getText());
        if (error == null) {
            JOptionPane.showMessageDialog(this, "Material updated successfully.");
            materialController.loadMaterials(tableModel);
        } else {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMUpdateActionPerformed

    private void btnMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDeleteActionPerformed
        String error = materialController.deleteMaterial(txtMMatID.getText());
        if (error == null) {
            JOptionPane.showMessageDialog(this, "Material deleted successfully.");
            materialController.loadMaterials(tableModel);
        } else {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMDeleteActionPerformed

    private void btnMReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMReturnActionPerformed
        DashboardForm dashboardForm = new DashboardForm();
        dashboardForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMReturnActionPerformed

    private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked
        int row = tblMaterial.getSelectedRow();
        if (row != -1) {
            txtMMatID.setText(tblMaterial.getValueAt(row, 0).toString());
            txtMMatName.setText(tblMaterial.getValueAt(row, 1).toString());
            txtMMatQuantity.setText(tblMaterial.getValueAt(row, 2).toString());
            txtMMatReorder.setText(tblMaterial.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_tblMaterialMouseClicked

    private void btnToggleThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleThemeActionPerformed
        util.ThemeManager.isDarkMode = !util.ThemeManager.isDarkMode;
        if (util.ThemeManager.isDarkMode) {
            applyDarkMode();
            btnToggleTheme.setText("☀ Light");
        } else {
            applyLightMode();
            btnToggleTheme.setText("🌙 Dark");
        }
    }//GEN-LAST:event_btnToggleThemeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MaterialFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMDelete;
    private javax.swing.JButton btnMReturn;
    private javax.swing.JButton btnMUpdate;
    private javax.swing.JButton btnMView;
    private javax.swing.JButton btnToggleTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtMMatID;
    private javax.swing.JTextField txtMMatName;
    private javax.swing.JTextField txtMMatQuantity;
    private javax.swing.JTextField txtMMatReorder;
    // End of variables declaration//GEN-END:variables
}
