/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import Controller.RegistrationController;
import util.DBConnection;
import javax.swing.JOptionPane;
/**
 *
 * @author Paul
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());

    private void applyDarkMode() {
        getContentPane().setBackground(new java.awt.Color(15, 23, 42));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(226, 232, 240));
        jLabel4.setForeground(new java.awt.Color(226, 232, 240));
        jLabel6.setForeground(new java.awt.Color(226, 232, 240));
        jLabel7.setForeground(new java.awt.Color(226, 232, 240));
        jLabel8.setForeground(new java.awt.Color(226, 232, 240));
        lblRLogin.setForeground(new java.awt.Color(148, 163, 184));
        txtRFName.setBackground(new java.awt.Color(30, 41, 59));
        txtRFName.setForeground(java.awt.Color.WHITE);
        txtRFName.setCaretColor(java.awt.Color.WHITE);
        txtRLName.setBackground(new java.awt.Color(30, 41, 59));
        txtRLName.setForeground(java.awt.Color.WHITE);
        txtRLName.setCaretColor(java.awt.Color.WHITE);
        txtREmail.setBackground(new java.awt.Color(30, 41, 59));
        txtREmail.setForeground(java.awt.Color.WHITE);
        txtREmail.setCaretColor(java.awt.Color.WHITE);
        ptxtRPassword.setBackground(new java.awt.Color(30, 41, 59));
        ptxtRPassword.setForeground(java.awt.Color.WHITE);
        ptxtRPassword.setCaretColor(java.awt.Color.WHITE);
        ptxtRCPassword.setBackground(new java.awt.Color(30, 41, 59));
        ptxtRCPassword.setForeground(java.awt.Color.WHITE);
        ptxtRCPassword.setCaretColor(java.awt.Color.WHITE);
        
        lblRole.setForeground(new java.awt.Color(226, 232, 240));
        cmbRole.setBackground(new java.awt.Color(51, 65, 85));
        cmbRole.setForeground(java.awt.Color.WHITE);
        
        repaint();
    }

    private void applyLightMode() {
        getContentPane().setBackground(new java.awt.Color(248, 250, 252));
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel3.setForeground(new java.awt.Color(15, 23, 42));
        jLabel4.setForeground(new java.awt.Color(15, 23, 42));
        jLabel6.setForeground(new java.awt.Color(15, 23, 42));
        jLabel7.setForeground(new java.awt.Color(15, 23, 42));
        jLabel8.setForeground(new java.awt.Color(15, 23, 42));
        lblRLogin.setForeground(new java.awt.Color(100, 116, 139));
        txtRFName.setBackground(java.awt.Color.WHITE);
        txtRFName.setForeground(java.awt.Color.BLACK);
        txtRFName.setCaretColor(java.awt.Color.BLACK);
        txtRLName.setBackground(java.awt.Color.WHITE);
        txtRLName.setForeground(java.awt.Color.BLACK);
        txtRLName.setCaretColor(java.awt.Color.BLACK);
        txtREmail.setBackground(java.awt.Color.WHITE);
        txtREmail.setForeground(java.awt.Color.BLACK);
        txtREmail.setCaretColor(java.awt.Color.BLACK);
        ptxtRPassword.setBackground(java.awt.Color.WHITE);
        ptxtRPassword.setForeground(java.awt.Color.BLACK);
        ptxtRPassword.setCaretColor(java.awt.Color.BLACK);
        ptxtRCPassword.setBackground(java.awt.Color.WHITE);
        ptxtRCPassword.setForeground(java.awt.Color.BLACK);
        ptxtRCPassword.setCaretColor(java.awt.Color.BLACK);
        
        lblRole.setForeground(new java.awt.Color(15, 23, 42));
        cmbRole.setBackground(java.awt.Color.WHITE);
        cmbRole.setForeground(java.awt.Color.BLACK);
        
        repaint();
    }

    public RegistrationForm() {
        initComponents();
        setLocationRelativeTo(null);
        if (util.ThemeManager.isDarkMode) {
            applyDarkMode();
            btnToggleTheme.setText("☀ Light");
        } else {
            applyLightMode();
            btnToggleTheme.setText("🌙 Dark");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRFName = new javax.swing.JTextField();
        txtRLName = new javax.swing.JTextField();
        txtREmail = new javax.swing.JTextField();
        ptxtRPassword = new javax.swing.JPasswordField();
        ptxtRCPassword = new javax.swing.JPasswordField();
        btnRRegister = new javax.swing.JButton();
        btnRReturn = new javax.swing.JButton();
        lblRLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnToggleTheme = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Registration");

        txtRFName.addActionListener(this::txtRFNameActionPerformed);

        btnRRegister.setText("Register");
        btnRRegister.addActionListener(this::btnRRegisterActionPerformed);

        btnRReturn.setText("Cancel");
        btnRReturn.addActionListener(this::btnRReturnActionPerformed);

        lblRLogin.setText("If you are already registered click here.");
        lblRLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRLoginMouseClicked(evt);
            }
        });

        jLabel3.setText("Firstname");

        jLabel4.setText("Lastname");

        jLabel6.setText("Email");

        jLabel7.setText("Password");

        jLabel8.setText("Confirm Password");

        btnToggleTheme.setText("☀ Light");
        btnToggleTheme.addActionListener(this::btnToggleThemeActionPerformed);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Storekeeper", "Supervisor" }));

        lblRole.setText("Role");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118)
                        .addComponent(btnToggleTheme)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRReturn)
                                    .addComponent(btnRRegister))
                                .addGap(78, 78, 78)))
                        .addGap(180, 180, 180))))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(lblRole))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtRLName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRFName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtREmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ptxtRPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ptxtRCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnToggleTheme)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtREmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptxtRPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptxtRCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblRLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRReturn)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final RegistrationController registrationController = new RegistrationController();
    
    private void txtRFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFNameActionPerformed

    private void btnRReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRReturnActionPerformed
        registrationController.goToLogin(this);
    }//GEN-LAST:event_btnRReturnActionPerformed

    private void btnRRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRRegisterActionPerformed
        String error = registrationController.register(
        txtRFName.getText(), txtRLName.getText(), txtREmail.getText(),
        new String(ptxtRPassword.getPassword()), new String(ptxtRCPassword.getPassword()),cmbRole.getSelectedItem().toString());
        if (error == null) {
            JOptionPane.showMessageDialog(this, "Registration successful!");
            registrationController.goToLogin(this);
        } 
        else {
            JOptionPane.showMessageDialog(this, error, "Registration Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRRegisterActionPerformed

    private void lblRLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRLoginMouseClicked
        registrationController.goToLogin(this);
    }//GEN-LAST:event_lblRLoginMouseClicked

    private void btnToggleThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleThemeActionPerformed
        util.ThemeManager.isDarkMode = !util.ThemeManager.isDarkMode;
        if (util.ThemeManager.isDarkMode) {
            applyDarkMode();
            btnToggleTheme.setText("☀ Light");
        } else {
            applyLightMode();
            btnToggleTheme.setText("🌙 Dark");
        }
    }//GEN-LAST:event_btnToggleThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRRegister;
    private javax.swing.JButton btnRReturn;
    private javax.swing.JButton btnToggleTheme;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblRLogin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPasswordField ptxtRCPassword;
    private javax.swing.JPasswordField ptxtRPassword;
    private javax.swing.JTextField txtREmail;
    private javax.swing.JTextField txtRFName;
    private javax.swing.JTextField txtRLName;
    // End of variables declaration//GEN-END:variables
}
